apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: llm
  namespace: agentgateway-system
spec:
  ai:
    groups:
      - providers:
          - name: ollama-home-pc
            host: 192.168.0.152
            port: 11434
            openai:
              model: qwen2.5:latest
      - providers:
          - name: openai-fallback
            openai:
              model: gpt-4o-mini
            policies:
              auth:
                secretRef:
                  name: openai-secret
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: llm
  namespace: agentgateway-system
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: agentgateway-proxy
      namespace: agentgateway-system
  rules:
    - backendRefs:
        - name: llm
          namespace: agentgateway-system
          group: agentgateway.dev
          kind: AgentgatewayBackend
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
