apiVersion: v1
kind: ConfigMap
metadata:
  name: agentgateway-proxy-tracing
  namespace: agentgateway-system
data:
  config.yaml: |
    config: {}
    tracing:
      endpoint: "http://phoenix-svc.phoenix.svc.cluster.local:4317"
      protocol: grpc
      random_sampling: true
      path: "/v1/traces"
