apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://minipc.local/argocd
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.fataev.in.ua/realms/homelab
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups
