apiVersion: v1
kind: Secret
metadata:
    name: openai-secret
    namespace: agentgateway-system
type: Opaque
stringData:
    Authorization: ENC[AES256_GCM,data:XXRjmSsX8rfkXJ3uNpD1aXJtflRiu+BEgxp0Dr2RuYwPLTMENSr0efuK1bYQTkccaCdz3zNvo1eWypzjL0lHeyfJHoy8DyIaWf1MVdbJ01WObLk3UyA1YEELc2VZLJ3utoBiD/1MHbtKBaFiHxrJ56DppwWzPrNueK+gfboo6jdYBxy8jcDHuVoC9rr4u8cTfKTWKkXXSwWSFPccv2siEuHfQkLjdCqlsxal,iv:B23HJgsUWUJk5mJa/Q7diYwivVlvbxPeKJ2IU5qAtOY=,tag:OGqNxmVAs7sV/F7VjjnpDQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:682364461498:key/6b761dca-702a-4b5a-b995-be6302c81fe0
          created_at: "2026-03-27T00:44:50Z"
          enc: AQICAHgKX/kY1X2NV3dNANs1prn+ZBhtFE3CdD1OvIig21R9EwF81AqgT88AKNS0cmjQwPy3AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMF1JHpDZvUQzY0NF9AgEQgDsDvA9rt9WgaA7Y5am3+o4eHqWVwmImiggF1bF8Sj07zkMVl8pjQ577P034iWHFIxDWZHkYuH6pJGxi1A==
          aws_profile: ""
    lastmodified: "2026-03-27T00:44:50Z"
    mac: ENC[AES256_GCM,data:laCvs193bC8PGq7LdvVaWiWXNrRtdF3ciUs3mYMPFbVYopnOR5Sf9DJtGnv6puek7l9xfgJvxxBSZ7556IX+pJgGzSDPR2eAg9gbG5Qr1e9mgbtNbet4QMA/qzyjY/V+/m36Pz67fC8f6YApvsmMvvUwCZ8MRdIfSked8bXAtnY=,iv:AB5SlxlhQJyrF/3G3o00kyNrnBf/iiFNlsASZk+8tg8=,tag:wkJsT+dpXmrDTttThtfzsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
