apiVersion: v1
kind: Secret
metadata:
  name: repo-agentgateway-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: agentgateway-charts
  url: ghcr.io/kgateway-dev/charts
  enableOCI: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-kagent-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: kagent-charts
  url: ghcr.io/kagent-dev/kagent/helm
  enableOCI: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-qdrant-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: qdrant-charts
  url: https://qdrant.github.io/qdrant-helm
