apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-repos.yaml
  - ../../apps/agentgateway/overlays/minipc
  - ../../apps/kagent/overlays/minipc
  - ../../apps/phoenix/overlays/minipc
  - ../../apps/qdrant/overlays/minipc
  - ../../apps/ha-mcp/overlays/minipc
  - ../../apps/ollama/overlays/minipc
