apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://qdrant.github.io/qdrant-helm
    chart: qdrant
    targetRevision: "1.17.0"
    helm:
      valuesObject:
        replicaCount: 1
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: qdrant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
