apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phoenix
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        deployment:
          nodeSelector:
            node-pool: minipc
        service:
          type: ClusterIP
        ingress:
          enabled: false
