apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/fataevalex/fwdays-ai-sre.git
    targetRevision: main
    path: apps/agentgateway/flux
  destination:
    server: https://kubernetes.default.svc
    namespace: flux-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
