apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - argocd-app-gateway-api-crds.yaml
  - argocd-app-crds.yaml
  - argocd-app.yaml
  - argocd-app-config.yaml
  - argocd-app-secrets.yaml
