apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fwdays-ai-sre-kind
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fataevalex/fwdays-ai-sre.git
    targetRevision: main
    path: environments/kind
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
