apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - gateway.yaml
  - llm-backend.yaml

patches:
  - path: agentgateway-app-patch.yaml
    target:
      kind: Application
      name: agentgateway
