apiVersion: v1
kind: Secret
metadata:
    name: ha-mcp-token
    namespace: kagent
type: Opaque
stringData:
    authorization-header: ENC[AES256_GCM,data:yjWWtNtW4Wv709FMZ36LpRU+UFVM7Lr10xRWyFaMyU8x9szVnEvqEPUZP79P5ZhCL4wUXGrZEVEhn5gPuPRsXiUskKER/W+hy3Glb4q8HYitvo/5YNILkX6TRooi1Al3GVLnS+T/fgwrgzQXKo8E47PaKXaQYcfFSjHHgPXODhsOppz9BByPxZBNVtez0zYNNxlZzBkVZ+iQxfDa4I72wK9jgM6cvVwM4O0yhXowpBy20D0nV5V+RunHCbEDug==,iv:9FhRuYjrt1EPIMetRY6QNy5a+lPYMB00AEvCDPGTkDE=,tag:Xix4W3afcyicb6XMPKAM3w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:682364461498:key/6b761dca-702a-4b5a-b995-be6302c81fe0
          created_at: "2026-03-26T00:04:07Z"
          enc: AQICAHgKX/kY1X2NV3dNANs1prn+ZBhtFE3CdD1OvIig21R9EwEDdcjGs2zolAcUaipxdiEJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMeIaz347FR5ruGO0HAgEQgDvL9yUO7mUWL+IyaC1MFmHhUqs1+TnjodvH9dqtMnTDNNv19chaXj/UrDXO5l4q/zLY1kp5LU3hAHzn1g==
          aws_profile: ""
    lastmodified: "2026-03-26T00:04:07Z"
    mac: ENC[AES256_GCM,data:2rvqXY50PFb+gltzTIc1ra/YruYdfONa8TM3TFEy32/qQeQ6i2ZTS0i6wwAMh2m9QNYBSmqhL/QztaYZ4qAqLoRFE+rUG6CEjF7lB8R7/UVK3eFm2lXIoQpyiJHABySWgByCM7DGlmWLo3xXgraPNP4yu5MH0l7iOWWt/rRRajA=,iv:rpZmSMINbHGDqLk5VL2/fTOwkw6gzo1CArseZ0+4YTY=,tag:SmiXnWfhsBhZAL7/2jQuJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
