apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: kagent:kagent.dev/ModelConfig:kagent/default-model-config
  creationTimestamp: "2026-03-15T21:13:38Z"
  generation: 5
  labels:
    app.kubernetes.io/instance: kagent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kagent
    app.kubernetes.io/part-of: kagent
    app.kubernetes.io/version: 0.8.0-beta6
    helm.sh/chart: kagent-0.8.0-beta6
  name: default-model-config
  namespace: kagent
  resourceVersion: "30587905"
  uid: 823531ef-571c-4c9c-8220-8c2f3970ed7d
spec:
  apiKeySecret: kagent-openai
  apiKeySecretKey: OPENAI_API_KEY
  model: gpt-4o-mini
  openAI:
    baseUrl: http://agentgateway-proxy.agentgateway-system.svc.cluster.local:8080/v1
  provider: OpenAI
status:
  conditions:
  - lastTransitionTime: "2026-03-15T21:11:16Z"
    message: Model configuration accepted
    reason: ModelConfigReconciled
    status: "True"
    type: Accepted
  observedGeneration: 5
  secretHash: value-closed
