apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fwdays-ai-sre
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/fataevalex/fwdays-ai-sre.git
  ref:
    branch: main
