apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ha-mcp-secrets
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: fwdays-ai-sre
  path: ./apps/ha-mcp/overlays/minipc/secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: kube2iam-aws-credentials
