apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        providers:
          default: openAI
          openAI:
            provider: OpenAI
            model: "llama3.1:8b"
            apiKey: "dummy"
            config:
              baseUrl: "http://agentgateway-proxy.agentgateway-system.svc.cluster.local/v1"
        nodeSelector:
          node-pool: minipc
        controller:
          nodeSelector:
            node-pool: minipc
        ui:
          service:
            type: ClusterIP
          nodeSelector:
            node-pool: minipc
        kmcp:
          nodeSelector:
            node-pool: minipc
        kagent-tools:
          nodeSelector:
            node-pool: minipc
        grafana-mcp:
          nodeSelector:
            node-pool: minipc
        querydoc:
          nodeSelector:
            node-pool: minipc
        agents:
          k8s-agent:
            enabled: true
          observability-agent:
            enabled: false
          kgateway-agent:
            enabled: false
          istio-agent:
            enabled: false
          promql-agent:
            enabled: false
          argo-rollouts-agent:
            enabled: false
          helm-agent:
            enabled: false
          cilium-policy-agent:
            enabled: false
          cilium-manager-agent:
            enabled: false
          cilium-debug-agent:
            enabled: false
