apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: kagent-app-patch.yaml
    target:
      kind: Application
      name: kagent
  - path: kagent-nginx-patch-app-patch.yaml
    target:
      kind: Application
      name: kagent-nginx-patch
